services:
  app:
    image: gotodo
    build:
      args:
        - target=deploy
    environment:
      LAB_ENV: dev
      PORT: 8080
      LAB_DB_HOST: lab-db
      LAB_DB_PORT: 3306
      LAB_DB_USER: lab
      LAB_DB_PASSWORD: lab
      LAB_DB_DATABASE: lab
    volumes:
     - .:/app
    ports:
      - "18000:8080"
  lab-db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: lab-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: lab
      MYSQL_PASSWORD: lab
      MYSQL_DATABASE: lab
    volumes:
      - lab-db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"

volumes:
  lab-db-data:
