kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  extraPortMappings:
    - containerPort: 30599
      hostPort: 8080
# the three workers
- role: worker
- role: worker
- role: worker