apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: ghcr.io/static-fuji/lab-quiz-app:1.0.1
        ports:
        - containerPort: 8080
        env:
        - name: LAB_ENV
          value: "dev"
        - name: PORT
          value: "8080"
        - name: LAB_DB_HOST
          value: "db-service"
        - name: LAB_DB_PORT
          value: "3306"
        - name: LAB_DB_USER
          value: "lab"
        - name: LAB_DB_PASSWORD
          value: "lab"
        - name: LAB_DB_DATABASE
          value: "lab"