// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package handler

import (
	"context"
	"github.com/static-fuji/lab_quiz/entity"
	"sync"
)

// Ensure, that ListWordsServiceMock does implement ListWordsService.
// If this is not the case, regenerate this file with moq.
var _ ListWordsService = &ListWordsServiceMock{}

// ListWordsServiceMock is a mock implementation of ListWordsService.
//
//	func TestSomethingThatUsesListWordsService(t *testing.T) {
//
//		// make and configure a mocked ListWordsService
//		mockedListWordsService := &ListWordsServiceMock{
//			ListWordsFunc: func(ctx context.Context) (entity.Words, error) {
//				panic("mock out the ListWords method")
//			},
//		}
//
//		// use mockedListWordsService in code that requires ListWordsService
//		// and then make assertions.
//
//	}
type ListWordsServiceMock struct {
	// ListWordsFunc mocks the ListWords method.
	ListWordsFunc func(ctx context.Context) (entity.Words, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListWords holds details about calls to the ListWords method.
		ListWords []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockListWords sync.RWMutex
}

// ListWords calls ListWordsFunc.
func (mock *ListWordsServiceMock) ListWords(ctx context.Context) (entity.Words, error) {
	if mock.ListWordsFunc == nil {
		panic("ListWordsServiceMock.ListWordsFunc: method is nil but ListWordsService.ListWords was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListWords.Lock()
	mock.calls.ListWords = append(mock.calls.ListWords, callInfo)
	mock.lockListWords.Unlock()
	return mock.ListWordsFunc(ctx)
}

// ListWordsCalls gets all the calls that were made to ListWords.
// Check the length with:
//
//	len(mockedListWordsService.ListWordsCalls())
func (mock *ListWordsServiceMock) ListWordsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListWords.RLock()
	calls = mock.calls.ListWords
	mock.lockListWords.RUnlock()
	return calls
}

// Ensure, that AddWordServiceMock does implement AddWordService.
// If this is not the case, regenerate this file with moq.
var _ AddWordService = &AddWordServiceMock{}

// AddWordServiceMock is a mock implementation of AddWordService.
//
//	func TestSomethingThatUsesAddWordService(t *testing.T) {
//
//		// make and configure a mocked AddWordService
//		mockedAddWordService := &AddWordServiceMock{
//			AddWordFunc: func(ctx context.Context, title string, desc string, lab string, articleID []int) (*entity.Word, error) {
//				panic("mock out the AddWord method")
//			},
//			SearchArticleIDFunc: func(ctx context.Context, id int) error {
//				panic("mock out the SearchArticleID method")
//			},
//		}
//
//		// use mockedAddWordService in code that requires AddWordService
//		// and then make assertions.
//
//	}
type AddWordServiceMock struct {
	// AddWordFunc mocks the AddWord method.
	AddWordFunc func(ctx context.Context, title string, desc string, lab string, articleID []int) (*entity.Word, error)

	// SearchArticleIDFunc mocks the SearchArticleID method.
	SearchArticleIDFunc func(ctx context.Context, id int) error

	// calls tracks calls to the methods.
	calls struct {
		// AddWord holds details about calls to the AddWord method.
		AddWord []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Title is the title argument value.
			Title string
			// Desc is the desc argument value.
			Desc string
			// Lab is the lab argument value.
			Lab string
			// ArticleID is the articleID argument value.
			ArticleID []int
		}
		// SearchArticleID holds details about calls to the SearchArticleID method.
		SearchArticleID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
	}
	lockAddWord         sync.RWMutex
	lockSearchArticleID sync.RWMutex
}

// AddWord calls AddWordFunc.
func (mock *AddWordServiceMock) AddWord(ctx context.Context, title string, desc string, lab string, articleID []int) (*entity.Word, error) {
	if mock.AddWordFunc == nil {
		panic("AddWordServiceMock.AddWordFunc: method is nil but AddWordService.AddWord was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Title     string
		Desc      string
		Lab       string
		ArticleID []int
	}{
		Ctx:       ctx,
		Title:     title,
		Desc:      desc,
		Lab:       lab,
		ArticleID: articleID,
	}
	mock.lockAddWord.Lock()
	mock.calls.AddWord = append(mock.calls.AddWord, callInfo)
	mock.lockAddWord.Unlock()
	return mock.AddWordFunc(ctx, title, desc, lab, articleID)
}

// AddWordCalls gets all the calls that were made to AddWord.
// Check the length with:
//
//	len(mockedAddWordService.AddWordCalls())
func (mock *AddWordServiceMock) AddWordCalls() []struct {
	Ctx       context.Context
	Title     string
	Desc      string
	Lab       string
	ArticleID []int
} {
	var calls []struct {
		Ctx       context.Context
		Title     string
		Desc      string
		Lab       string
		ArticleID []int
	}
	mock.lockAddWord.RLock()
	calls = mock.calls.AddWord
	mock.lockAddWord.RUnlock()
	return calls
}

// SearchArticleID calls SearchArticleIDFunc.
func (mock *AddWordServiceMock) SearchArticleID(ctx context.Context, id int) error {
	if mock.SearchArticleIDFunc == nil {
		panic("AddWordServiceMock.SearchArticleIDFunc: method is nil but AddWordService.SearchArticleID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockSearchArticleID.Lock()
	mock.calls.SearchArticleID = append(mock.calls.SearchArticleID, callInfo)
	mock.lockSearchArticleID.Unlock()
	return mock.SearchArticleIDFunc(ctx, id)
}

// SearchArticleIDCalls gets all the calls that were made to SearchArticleID.
// Check the length with:
//
//	len(mockedAddWordService.SearchArticleIDCalls())
func (mock *AddWordServiceMock) SearchArticleIDCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockSearchArticleID.RLock()
	calls = mock.calls.SearchArticleID
	mock.lockSearchArticleID.RUnlock()
	return calls
}

// Ensure, that AddArticleServiceMock does implement AddArticleService.
// If this is not the case, regenerate this file with moq.
var _ AddArticleService = &AddArticleServiceMock{}

// AddArticleServiceMock is a mock implementation of AddArticleService.
//
//	func TestSomethingThatUsesAddArticleService(t *testing.T) {
//
//		// make and configure a mocked AddArticleService
//		mockedAddArticleService := &AddArticleServiceMock{
//			AddArticleFunc: func(ctx context.Context, title string, author string) (*entity.Article, error) {
//				panic("mock out the AddArticle method")
//			},
//		}
//
//		// use mockedAddArticleService in code that requires AddArticleService
//		// and then make assertions.
//
//	}
type AddArticleServiceMock struct {
	// AddArticleFunc mocks the AddArticle method.
	AddArticleFunc func(ctx context.Context, title string, author string) (*entity.Article, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddArticle holds details about calls to the AddArticle method.
		AddArticle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Title is the title argument value.
			Title string
			// Author is the author argument value.
			Author string
		}
	}
	lockAddArticle sync.RWMutex
}

// AddArticle calls AddArticleFunc.
func (mock *AddArticleServiceMock) AddArticle(ctx context.Context, title string, author string) (*entity.Article, error) {
	if mock.AddArticleFunc == nil {
		panic("AddArticleServiceMock.AddArticleFunc: method is nil but AddArticleService.AddArticle was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Title  string
		Author string
	}{
		Ctx:    ctx,
		Title:  title,
		Author: author,
	}
	mock.lockAddArticle.Lock()
	mock.calls.AddArticle = append(mock.calls.AddArticle, callInfo)
	mock.lockAddArticle.Unlock()
	return mock.AddArticleFunc(ctx, title, author)
}

// AddArticleCalls gets all the calls that were made to AddArticle.
// Check the length with:
//
//	len(mockedAddArticleService.AddArticleCalls())
func (mock *AddArticleServiceMock) AddArticleCalls() []struct {
	Ctx    context.Context
	Title  string
	Author string
} {
	var calls []struct {
		Ctx    context.Context
		Title  string
		Author string
	}
	mock.lockAddArticle.RLock()
	calls = mock.calls.AddArticle
	mock.lockAddArticle.RUnlock()
	return calls
}

// Ensure, that ListArticlesServiceMock does implement ListArticlesService.
// If this is not the case, regenerate this file with moq.
var _ ListArticlesService = &ListArticlesServiceMock{}

// ListArticlesServiceMock is a mock implementation of ListArticlesService.
//
//	func TestSomethingThatUsesListArticlesService(t *testing.T) {
//
//		// make and configure a mocked ListArticlesService
//		mockedListArticlesService := &ListArticlesServiceMock{
//			ListArticlesFunc: func(ctx context.Context) (entity.Articles, error) {
//				panic("mock out the ListArticles method")
//			},
//		}
//
//		// use mockedListArticlesService in code that requires ListArticlesService
//		// and then make assertions.
//
//	}
type ListArticlesServiceMock struct {
	// ListArticlesFunc mocks the ListArticles method.
	ListArticlesFunc func(ctx context.Context) (entity.Articles, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListArticles holds details about calls to the ListArticles method.
		ListArticles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockListArticles sync.RWMutex
}

// ListArticles calls ListArticlesFunc.
func (mock *ListArticlesServiceMock) ListArticles(ctx context.Context) (entity.Articles, error) {
	if mock.ListArticlesFunc == nil {
		panic("ListArticlesServiceMock.ListArticlesFunc: method is nil but ListArticlesService.ListArticles was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListArticles.Lock()
	mock.calls.ListArticles = append(mock.calls.ListArticles, callInfo)
	mock.lockListArticles.Unlock()
	return mock.ListArticlesFunc(ctx)
}

// ListArticlesCalls gets all the calls that were made to ListArticles.
// Check the length with:
//
//	len(mockedListArticlesService.ListArticlesCalls())
func (mock *ListArticlesServiceMock) ListArticlesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListArticles.RLock()
	calls = mock.calls.ListArticles
	mock.lockListArticles.RUnlock()
	return calls
}

// Ensure, that WordSearchServiceMock does implement WordSearchService.
// If this is not the case, regenerate this file with moq.
var _ WordSearchService = &WordSearchServiceMock{}

// WordSearchServiceMock is a mock implementation of WordSearchService.
//
//	func TestSomethingThatUsesWordSearchService(t *testing.T) {
//
//		// make and configure a mocked WordSearchService
//		mockedWordSearchService := &WordSearchServiceMock{
//			ListBindFunc: func(ctx context.Context, id int) (entity.Words, error) {
//				panic("mock out the ListBind method")
//			},
//		}
//
//		// use mockedWordSearchService in code that requires WordSearchService
//		// and then make assertions.
//
//	}
type WordSearchServiceMock struct {
	// ListBindFunc mocks the ListBind method.
	ListBindFunc func(ctx context.Context, id int) (entity.Words, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListBind holds details about calls to the ListBind method.
		ListBind []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
	}
	lockListBind sync.RWMutex
}

// ListBind calls ListBindFunc.
func (mock *WordSearchServiceMock) ListBind(ctx context.Context, id int) (entity.Words, error) {
	if mock.ListBindFunc == nil {
		panic("WordSearchServiceMock.ListBindFunc: method is nil but WordSearchService.ListBind was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockListBind.Lock()
	mock.calls.ListBind = append(mock.calls.ListBind, callInfo)
	mock.lockListBind.Unlock()
	return mock.ListBindFunc(ctx, id)
}

// ListBindCalls gets all the calls that were made to ListBind.
// Check the length with:
//
//	len(mockedWordSearchService.ListBindCalls())
func (mock *WordSearchServiceMock) ListBindCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockListBind.RLock()
	calls = mock.calls.ListBind
	mock.lockListBind.RUnlock()
	return calls
}
